name: CI - App
on:
  push:
    branches: [main, staging]
  pull_request:
    branches: [main, staging]
jobs:
  build:
    env:
      SKIP_ENV_VALIDATION: true
    name: Build Next.js app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "pnpm"
      - name: Install packages
        run: pnpm install --frozen-lockfile
      - name: Generate prisma types
        run: pnpm prisma generate
      - name: Build
        run: pnpm build
